import { useEffect, useState, useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import Slider from "../components/Slider";
import styles from "../styles/Home.module.css";
import { sanityClient, urlFor } from "../lib/sanity";
import Link from "next/link";

const heroDataQuery = `*[_type == "home_slider"]`;
const logosDataQuery = `*[_type == "logos"]`;

export default function Home({ heroData, logosData }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Slider heroData={heroData} />

        <section className={styles.about}>
          <div className={styles.bigText}>
            <h5>
              I am a front-end developer based in Queensland, Australia. I
              mainly work with react, next.js and/or WordPress.
            </h5>
          </div>
          <div className={styles.littleText}>
            <p>
              I have been working in Web Development since 2014 in both remote
              and office settings. Below is my preferred tech stack but I am
              always open to learning new tools for to overcome a particular
              challenge.
            </p>
          </div>
        </section>

        <section className={styles.logoContainer}>
          <h3>A few folks I have worked with.</h3>
          <div className={styles.logos}>
            <div className={styles.logo}>
              <img src="/mn.jpg" alt="" srcset="" />
            </div>
            <div className={styles.logo}>
              <img src="/the-coding-company-1.webp" alt="" srcset="" />
            </div>
            <div className={styles.logo}>
              <img
                src="/hervey-bay-seafood-fesitval-logo.svg"
                alt=""
                srcset=""
              />
            </div>
            <div className={styles.logo}>
              <img src="/fcte-logo-black.png" alt="" srcset="" />
            </div>
            <div className={styles.logo}>
              <img src="/qg-coa-ogp.png" alt="" srcset="" />
            </div>
            <div className={styles.logo}>
              <img src="/vivere.jpg" alt="" srcset="" />
            </div>
          </div>
        </section>

        <section className={styles.projects}>
          <div className={styles.project}>
            <h5>Hervey Bay Seafood Festival</h5>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit.
              Incidunt, in autem vitae pariatur alias officia quidem? Magni
              deserunt ad nulla?
            </p>
            <Link href="#">
              <a>View Project</a>
            </Link>
            <img src="/hbsf header.png" alt="" />
          </div>
        </section>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const heroData = await sanityClient.fetch(heroDataQuery);
  const logosData = await sanityClient.fetch(logosDataQuery);

  return { props: { heroData, logosData } };
}
